language: php

os:
  - linux

dist: xenial

php:
  - 7.4.22

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - composer install --no-interaction

script:
  - vendor/bin/pest --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
